### PR TITLE
Prevent basic auth from breaking WP CLI

### LINKED ISSUE #4: `require_auth()` function breaks WP CLI access
The `HM\BasicAuth\require_auth` function is being run outside of a hook, which means that things like WP CLI commands, where basic auth parameters aren't set, don't work. I don't know where the best place to hook this is, but it seems like it would be good to run it inside a hook to make sure we only prompt for basic auth in web requests.

### PR DESCRIPTION
**Pull request by jazzsequence**
* Adds `WP_CLI`, `DOING_AJAX` &  `DOING_CRON` as exclusions to `is_development_environment()` so basic auth is not run if any of those are true.

**Todo:** add unit tests for REST requests. #9 

resolves #4

### CODE REVIEW

**Review by goldenapples — COMMENTED** [review]
I haven't tested yet, but I suspect that `muplugins_loaded` gets fired in wp-cli processes, Cavalcade jobs, etc and will cause issues there. We probably need to find a hook that's only fired in a web request.

**Comment by jazzsequence** [comment]
@goldenapples [wp_loaded](https://developer.wordpress.org/reference/hooks/wp_loaded/) fires after everything (themes, plugins, wp) has been loaded and _might_ not fire in wp-cli, but I'm not sure. It's also really late and I'd rather hook in earlier, before headers are sent...

Maybe we need to explicitly disable in WP-CLI.

**Comment by jazzsequence** [comment]
[This SE post](https://wordpress.stackexchange.com/questions/301282/how-i-prevent-a-plugin-to-be-loaded-when-doing-wp-cli) refers to the `WP_CLI` global, so we could include that in our checks to enable/disable by default.

**Comment by goldenapples** [comment]
Sure. Let's also check for DOING_CRON in that case. 

We should also check to make sure Ajax and REST requests don't break. I would think they'd be fine once auth params are set in the browser but there could well be cross domain issues I'm not thinking of, especially in multisite.

**Review by goldenapples — APPROVED** [review]
Logic looks good, though it was initially hard for me to follow (I would have thought a variable named $ajax would be true in an Ajax request; as it is, we're checking if NOT in Ajax).

**Pull request merged**
